<?php
defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage contentblock : controller_template - admincp\action.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>

<form class="" action="<?php echo Linko::Url()->make('self'); ?>" method="post">
    <div class="row-fluid">
        <div class="pull-right">
            <input type="submit" class="btn btn-primary admin-submit-button" value="<?php echo(isset($aBlock['contentblock_id']) ? 'Update Block' : 'Create Block'); ?>" />
        </div>
    </div>
    <div class="row-fluid">
        <div class="box span8" onTablet="span12" onDesktop="span8">
            <div class="box-header">
                <h2><i class="icon-edit"></i><span class="break"></span><?php echo(isset($aBlock['contentblock_id']) ? 'Edit Block' : 'New Block'); ?></h2>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <label class="control-label" for="focusedInput">Title</label>
                    <div class="controls">
                        <input class="span12 focused" type="text" name="val[title]" value="<?php echo Arr::get($aVals, 'title', Arr::get($aBlock, 'title', '')); ?>">
                    </div>
                </div>
                <div class="control-group hidden-phone">
                    <label class="control-label" for="textarea2">Content</label>
                    <div class="controls">
                        <textarea id="textarea2" class="span12" rows="10" name="val[text]"><?php echo Arr::get($aVals, 'text', Arr::get($aBlock, 'text', '')); ?></textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="box span4 noMargin" onTablet="span12" onDesktop="span4">
            <div class="box-header">
                <h2><i class="icon-tasks"></i><span class="break"></span>Options</h2>
            </div>
            <div class="box-content">
            </div>
        </div>  

    </div>
</form>