<?php

defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage contentblock : controller_template - admincp\index.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>
<?php if(count($aBlocks)): ?>
    <form class="form-inline" action="<?php echo Linko::Url()->make('self'); ?>" method="post">
        <a class="btn small" href="<?php echo Linko::Url()->make('contentblock:admincp:action', array('action' => 'add')); ?>">Create Content Block</a>
        <div class="row-fluid sortable">		
            <div class="box span12">
                <div class="box-header" data-original-title>
                    <h2><i class="icon-edit"></i><span class="break"></span>All Content Blocks</h2>
                </div>
                <div class="box-content">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th class="span6">Content</th>
                                <th>Actions</th>
                            </tr>
                        </thead>   
                        <tbody>
                            <?php foreach($aBlocks as $aBlock): ?>
                                <tr>
                                    <td class="center"><?php echo $aBlock['title']; ?></td>
                                    <td class="center"><?php echo strip_tags($aBlock['text']); ?></td>
                                    <td class="center">
                                        <a class="btn btn-mini btn-inverse" href="<?php echo Linko::Url()->make('contentblock:admincp:action', array('action' => 'edit', 'id' => $aBlock['contentblock_id'])); ?>">
                                            <i class="">Edit</i>  
                                        </a>
                                        <a class="btn btn-mini btn-danger" href="<?php echo Linko::Url()->make('contentblock:admincp:action', array('action' => 'delete', 'id' => $aBlock['contentblock_id'])); ?>">
                                            <i class="">Delete</i> 
                                        </a>
                                    </td>
                                </tr>  
                            <?php endforeach; ?>
                        </tbody>
                    </table>  
                </div>
            </div><!--/span-->                   
        </div><!--/row-->
    </form> 
<?php else: ?>
    <div class="row-fluid sortable">		
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="icon-edit"></i><span class="break"></span>All Post</h2>
            </div>
            <div class="box-content">
                <h4>
                    No Content Blocks Created.
                </h4>
                <h6>
                    <a href="<?php echo Linko::Url()->make('contentblock:admincp:action', array('action' => 'add')); ?>">Click here</a> to add a new Content Block.
                </h6>
            </div>
        </div>
    </div>
<?php endif; ?>
