<?php defined('LINKO') or exit;

/**
 * @package Mobile
 * @author Morrison Laju <morrelinko@gmail.com>
 * @var $this Linko_Application_Template
 */
?>
<!DOCTYPE html>
<html>
<head>
<title><?php echo $this->getTitle(); ?></title>
<?php echo $this->getHeader(); ?>
</head>
<body>
<div id="wrapper">
	<div id="header" class="clearfix">
        <a href="<?php echo $this->url('mobile:dashboard'); ?>" id="logo">
            <h1><?php echo Linko::Module()->getSetting('page.site_title'); ?></h1>
        </a>
	</div>
	<div id="content">
		<?php echo $this->getContent(); ?>
	</div>
    <div id="footer">
        <p class="copyright">&copy; Copyright <?php echo Linko::Module()->getSetting('page.site_title'); ?></p>
        <div class="footer-links">
            <a href="<?php echo $this->url(null); ?>" class="footer-full-site"><?php echo Lang::t('mobile.goto_fullsite'); ?></a> |
            <a href="<?php echo $this->url('user:logout'); ?>"><?php echo Lang::t('user.logout'); ?></a>
        </div>

        <p class="powered-by">Powered by <a href="http://linkodev.com">LinkoPlatform</a> authored by Morrison Laju</p>
    </div>
</div>
<?php echo $this->getFooter(); ?>
</body>
</html>