<?php defined('LINKO') or exit; ?>


<div class="license">
    <p>This LinkoCMS License Agreement ("Agreement") is a legal agreement between you and Netaviva Limited ("Netaviva") for the licensing of the LinkoCMS software, which includes computer software and any associated media ("Software").</p>

<p>LinkoCMS, its source code and files are original works exclusively owned by Netaviva and subject to copyright laws and international copyright treaties, as well as other intellectual property laws and treaties.</p>

<p>Any and all intellectual property rights in the Software, including the original works, or parts thereof, in any form, are and shall remain the exclusive property of Netaviva and/or its licensors. Nothing in this Agreement intends to transfer any such intellectual property rights to you. You will not take any action to jeopardize, limit or interfere with Netaviva's rights.</p>

<p>Subject to the terms of this Agreement, Netaviva hereby grants you a limited, personal, non-exclusive, non-sublicensable, non-assignable license to download, install and use one instance of the Software and to use it on only one domain name extension (e.g. .com, .net, or .org). You may not rent, lease, sublicense, sell, assign, pledge, re-sell, transfer or otherwise dispose of the Software in any form, on a temporary or permanent basis, without the prior written consent of Netaviva. Netaviva reserves the right to refuse transfers at their sole discretion.</p>


<p>Netaviva may, but is not obligated to, provide you with updates or upgrades to the Software for free or subject to the payment of additional service fees. By installing, copying or otherwise using such update or upgrade, you agree to be bound by the terms of this Agreement with respect to such update or upgrade.</p>

<p>By using the Software, you agree to comply all legal obligations, including but not limited to obligations imposed by copyright, trade secrets, defamation, decency, privacy, security and export laws and any other applicable laws, regulations and policies that may apply.</p>

<p>The text, sounds, pictures, photos, video, software and/or any other type of information ("Content") or communications spread by the use of the Software is entirely the responsibility of the person or entity form whom such Content originated. The Content is not reviewed, controlled, examined, verified or endorsed by Netaviva in any way. You acknowledge and agree that you are solely responsible for any Content that you upload, submit, post, transmit or display through the Software and that Netaviva is not responsible to you or any third party for any Content that is uploaded, submitted, posted, transmitted or displayed through the Software by you or any other user of the Software.</p>

<p>You agree that you shall not upload, submit, post, transmit or display through the Software any Content that is subject to any third party intellectual property rights, unless you have a license or specific permission from the owner to upload, submit, post, transmit or display through the Software such third party content.</p>

<p>YOU AGREE TO INDEMNIFY, DEFEND AND HOLD NETAVIVA HARMLESS FROM AND AGAINST ANY AND ALL LIABILITY AND COSTS, INCLUDING REASONABLE ATTORNEYS' FEES INCURRED, IN CONNECTION WITH OR ARISING OUT OF YOUR (A) VIOLATION OR BREACH OF ANY TERM OF THIS AGREEMENT OR ANY APPLICABLE LAW OR REGULATION, WHETHER OR NOT REFERENCED HEREIN, OR (B) VIOLATION OF ANY RIGHTS OF ANY THIRD PARTY, OR (C) USE OR MISUSE OF THE SOFTWARE.</p>

<p>THE SOFTWARE IS LICENSED TO YOU "AS IS" AND ANY USE OF THE SOFTWARE IS AT YOUR OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NETAVIVA DISCLAIM ALL WARRANTIES AND CONDITIONS, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. NETAVIVA FURTHER DOES NOT WARRANT OR REPRESENT THAT THE SOFTWARE WILL ALWAYS BE AVAILABLE, ACCESSIBLE, UNINTERRUPTED, SECURE, COMPLETE AND ERROR-FREE.</p>

<p>THE SOFTWARE IS OFFERED ON THE EXPRESS UNDERSTANDING THAT NETAVIVA SHALL HAVE NO LIABILITY IN CONNECTION WITH OR ARISING FROM YOUR USE OF THE SOFTWARE. YOUR ONLY RIGHT OR REMEDY WITH RESPECT TO ANY PROBLEMS OR DISSATISFACTION WITH THE SOFTWARE IS TO IMMEDIATELY UNINSTALL AND CEASE USE OF SUCH SOFTWARE.</p>

<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL NETAVIVA BE LIABLE FOR ANY SPECIAL INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING BUT WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, BUSINESS INTERRUPTION, CORRUPTION OF FILES, LOSS OF BUSINESS INFORMATION OR ANY OTHER PECUNIARY LOSS) REGARDLESS OF CAUSE OR FORM OF ACTION, INCLUDING CONTRACT TORT OR NEGLIGENCE, ARISING OUT OF THE USE OF OR INABILITY TO USE THE SOFTWARE, EVEN IF NETAVIVA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>

<p>Netaviva accepts no responsibility for site content and any complaints received from any third party may result in license suspension or revocation if the matter cannot be resolved. This action is at the sole discretion of Netaviva and is intended to offer both parties time for reflection or advice, and license reinstatement is also at the sole discretion of Netaviva and not a judgment of the circumstances. Benc will comply with any requirement from any Court of Jurisdiction.</p>

<p>The Agreement shall be governed by and interpreted in accordance with the laws of Nigeria, without reference to its conflict of law principles, and shall be subject to the jurisdiction of the courts of Nigeria</p>.

<p>In addition to this Agreement, you have to comply with any and all rules and regulations for the use of the Software provided by Netaviva, applicable from time to time, including but not limited to the General LinkoCMS Forum Rules.</p>

<p>Please see below for further information.</p> 

<p><strong>Product Support Policy</strong></p>

<p>For our product support policy please check: http://www.linkodev.com/policy/</p>

<p><strong>Netaviva reserves the right to modify this Agreement or the terms of its policies at any time.</strong></p>

</div>

<br />

<div class="text-right">
<form action="<?php echo Linko::Url()->make('self'); ?>" method="post">
    <input type="checkbox" name="agree-license" /> I agree to the terms and conditions.
    <input type="submit" class="button" value="Next" />
</form>
</div>