<?php
defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage page : controller_template - admincp\action.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>

<form id="add-page" action="<?php echo Linko::Url()->make('self'); ?>" method="post">
    <?php if ($bEdit): ?>
        <input type="hidden" name="val[component_id]" value="<?php echo $aPage['component_id']; ?>" />
        <input type="hidden" name="val[page_type]" value="<?php echo $aPage['page_type']; ?>" />
    <?php endif; ?>
        <div class="row-fluid">
    <div class="pull-right">
        <input type="submit" class="btn btn-primary admin-submit-button" name="process[edit_page]" value="<?php echo $bEdit ? 'Save' : 'Create'; ?> Page" />
    </div>
        </div>
    <div class="row-fluid">
        <div class="box span8" onTablet="span12" onDesktop="span8">
            <div class="box-header">
                <h2><i class="icon-edit"></i><span class="break"></span>General</h2>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <label class="control-label" for="focusedInput">Page Title</label>
                    <div class="controls">
                        <input class="span12 focused" type="text" name="val[page_title]" value="<?php echo Arr::get($aVals, 'page_title', Arr::get($aPage, 'page_title', '')); ?>">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="focusedInput">Page Url</label>
                    <div class="controls">
                        <input class="span12 focused" type="text" id="page-url" name="val[page_url]" value="<?php echo Arr::get($aVals, 'page_url', Arr::get($aPage, 'page_url', '')); ?>">
                        <br/><?php echo Linko::Url()->make(); ?><span id="js-page-url"><?php echo Arr::get($aPage, 'page_url'); ?></span>
                    </div>
                    <script>
                        $('#page-url').keyup(function(){
                            var uri = $(this).val();
                            $('#js-page-url').html(uri);
                        });
                    </script>
                </div>
                <?php if ($bEdit == false || ($bEdit && $aPage['page_type'] != 'module')): ?>
                    <div class="control-group">
                        <label class="control-label" for="textarea2">Page Content</label>
                        <div class="controls">
                            <textarea id="textarea2" class="span12 js-editor-content" rows="10" name="val[page_content]"><?php echo Arr::get($aVals, 'page_content', Arr::get($aPage, 'page_content', '')); ?></textarea>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            <br/>
            <div class="box-header">
                <h2><i class="icon-edit"></i><span class="break"></span>Meta Data</h2>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <label class="control-label" for="meta-title">Meta Title</label>
                    <div class="controls">
                        <input class="span12 focused" type="text" id="meta-title" name="val[meta_title]" value="<?php echo Arr::get($aVals, 'meta_title', Arr::get($aPage, 'meta_title', '')); ?>">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="meta-keywords">Meta Keywords</label>
                    <div class="controls">
                        <input class="span12 focused" type="text" id="meta-keywords" name="val[meta_keywords]" value="<?php echo Arr::get($aVals, 'meta_keywords', Arr::get($aPage, 'meta_keywords', '')); ?>">
                    </div>
                </div>
                   <div class="control-group">
                        <label class="control-label" for="meta-description">Meta Description</label>
                        <div class="controls">
                            <textarea id="meta-description" class="span12" rows="5" name="val[meta_description]"><?php echo Arr::get($aVals, 'meta_description', Arr::get($aPage, 'meta_description', '')); ?></textarea>
                        </div>
                    </div>
            </div>
        </div>
 
        <div class="box span4 noMargin" onTablet="span12" onDesktop="span4">
            <div class="box-header">
                <h2><i class="icon-tasks"></i><span class="break"></span>Options</h2>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <label class="control-label inline" for="pagestatus">Page Status</label>
                    <div class="controls">
                        <ul class="select-blog-categories">
                            <select name="val[page_status]">
                                <option<?php echo((Arr::get($aVals, 'page_status', Arr::get($aPage, 'page_status', '')) == 0) ? ' selected="selected"' : null); ?> value="0">Hidden</option>
                                <option<?php echo((Arr::get($aVals, 'page_status', Arr::get($aPage, 'page_status', '')) == 1) ? ' selected="selected"' : null); ?> value="1">Active</option>
                            </select>
                        </ul>
                    </div>
                </div>
                <?php if ($bEdit == false): ?>
                    <div class="control-group">
                        <div class="controls">
                            <label class="checkbox inline">
                            <input type="checkbox" name="val[add_menu]" />Add to Menu
                            </label>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="control-group">
                    <div class="controls">
                        <label class="checkbox inline">
                        <input type="checkbox" name="val[is_homepage]"<?php echo Arr::get($aVals, 'is_homepage', Arr::get($aPage, 'is_homepage', '')) == 1 ? ' checked="checked"' : null; ?> />Is Homepage?
                        </label>
                    </div>
                </div>
            </div>
        </div> 

        <div class="box span4 noMargin" onTablet="span12" onDesktop="span4">
            <div class="box-header">
                <h2><i class="icon-tasks"></i><span class="break"></span>Template Layout</h2>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <div class="controls">
                        <ul class="select-blog-categories">
                            <select name="val[layout]">
                                <?php
                                $this->plugin('option', array(
                                    'data' => $aLayouts,
                                    'value_key' => 'name',
                                    'title_key' => 'title'
                                ));
                                ?>
                            </select>
                        </ul>
                    </div>
                </div>
            </div>
        </div> 
        <div class="box span4 noMargin" onTablet="span12" onDesktop="span4">
            <div class="box-header">
                <h2><i class="icon-filter"></i><span class="break"></span>Accessibility</h2>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <label class="control-label" for="pagestatus">Dissallow Access</label>
                    <div class="controls">
                        <ul class="select-blog-categories">
                            <?php foreach ($aUserRoles as $aRole): ?>
                             <label for="category-<?php echo $aRole['role_id']; ?>">
                                <input type="checkbox" name="val[dissallow_access][]"<?php echo(in_array($aRole['role_id'], Arr::get($aVals, 'dissallow_access', Arr::get($aPage, 'dissallow_access', array()))) ? ' checked="checked"' : null); ?> value="<?php echo $aRole['role_id']; ?>" />
                                <?php echo $aRole['role_title']; ?>
                             </label>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div> 

    </div>
</form>