<?php
defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage page : controller_template - admincp\index.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>

    <a class="btn small" href="<?php echo Linko::Url()->make('page:admincp:action', array('action' => 'add')); ?>">Add Page</a>
    <div class="row-fluid sortable">		
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="icon-edit"></i><span class="break"></span>Pages</h2>
            </div>
            <div class="box-content">
                <?php if (count($aPages)): ?>
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th> <!-- Icon --></th>
                                <th>Title</th>
                                <th>Home</th>
                                <th>Module</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>   
                        <tbody>
                            <?php foreach ($aPages as $aPage): ?>
                                <tr id="page-<?php echo $aPage['page_id']; ?>">
                                    <td><img src="<?php echo $this->getImage('file.png', 'module_page'); ?>" /></td>
                                    <td class="center"><?php echo $aPage['page_title']; ?></td>
                                    <td class="center"> <div title="Home Page" class="js-homepage-drop js-ui-homepage-drop">
                                            <?php if ((bool) $aPage['is_homepage']): ?>
                                                <img class="js-homepage-drag" src="<?php echo $this->getImage('home.png', 'module_page'); ?>" />
                                            <?php endif; ?>
                                        </div></td>
                                    <td class="center"><?php echo $aPage['module_id']; ?></td>
                                    <td class="center">
                                        <span class="page-status <?php echo strtolower($aPage['page_status']); ?>">
                                            <?php echo $aPage['page_status'] == 1 ? 'Active' : 'Inactive'; ?>
                                        </span>
                                    </td>
                                    <td class="center">
                                        <a class="btn btn-mini btn-inverse" href="<?php echo Linko::Url()->make('page:admincp:action', array('action' => 'edit', 'id' => $aPage['page_id'])); ?>">
                                            <i class="">Edit</i>
                                        </a>
                                        <a class="btn btn-mini btn-danger" href="<?php echo Linko::Url()->make('page:admincp:action', array('action' => 'delete', 'id' => $aPage['page_id'])); ?>">
                                            <i class="">Delete</i> 
                                        </a>
                                    </td>
                                </tr>  
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endif; ?>
                <p>
        <b>Setting Homepage: </b>Drag and drop the Home icon on the page you want to set as homepage
    </p>
            </div>
        </div><!--/span-->                   
    </div><!--/row-->


