<?php
defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage contest : controller_template - index.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>
<div id="contest-list-container">
    <?php foreach ($aContests as $aContest): ?>
        <div class="each-contest" >
            <div class="each-main-content">
                <div class="team_a teams">

                    <?php echo $aContest['contest_team_a']; ?>
                    <img src="<?php echo $this->getImage(array('post' => array('post_image' => $aContest['contest_team_a_logo']), 'size' =>150), 'contest_image')?>"/>
                </div>
                <div class="versus"> <h1><?php echo Lang::t('contest.contest_vs'); ?></h1><br /><?php echo Lang::t('contest.contest_draw_match'); ?><br /></div>
                <div class="team_b teams">
                    <?php echo $aContest['contest_team_b']; ?>
                    <img src="<?php echo $this->getImage(array('post' => array('post_image' => $aContest['contest_team_b_logo']), 'size' =>150), 'contest_image')?>"/>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div class="each-tools" id="my-<?php echo $aContest['contest_id']; ?>">
            <?php
            $contest_year = date("Y", strtotime($aContest['contest_end_date']));
            $contest_month = date("m", strtotime($aContest['contest_end_date']));
            $contest_month_c = date("M", strtotime($aContest['contest_end_date']));
            $contest_date = date("d", strtotime($aContest['contest_end_date']));
            $time_left = date("H,i,s", strtotime($aContest['contest_end_date']));
            ?>
            <script>
                jQuery(document).ready(function(){
                    var austDay = new Date();
                    austDay = new Date(<?php echo $contest_year; ?>, <?php echo $contest_month; ?>-1, <?php echo $contest_date; ?>,<?php echo $time_left ?>)
                    jQuery('#defaultCountdown<?php echo $aContest['contest_id']; ?>').countdown({until: austDay,layout:
                            '<div id="timer">' + ''+
                            '<div id="timer_days" class="timer_numbers">{dnn}</div>'+
                            '<div id="timer_hours" class="timer_numbers">{hnn}</div>'+ 
                            '<div id="timer_mins" class="timer_numbers">{mnn}</div>'+
                            '<div id="timer_seconds" class="timer_numbers">{snn}</div>'+
                            '<div id="timer_labels">'+
                            '<div id="timer_days_label" class="timer_labels">days</div>'+
                            '<div id="timer_hours_label" class="timer_labels">hours</div>'+
                            '<div id="timer_mins_label" class="timer_labels">mins</div>'+
                            '<div id="timer_seconds_label" class="timer_labels">secs</div>'+
                            '</div>'+							
                            '</div>'
                    });
                    jQuery('#year').text(austDay.getFullYear());
                });                
            </script>
            <div style="position: absolute;left: 10px; top: 1px;cursor: text;" id="defaultCountdown<?php echo $aContest['contest_id']; ?>"></div>
            <a  href="<?php echo $aContest['contest_url']; ?>" class="btn btn-info each-participate-button"><?php echo Lang::t('contest.view_match_details'); ?></a>    
        </div>
    <?php endforeach; ?>
</div>
<?php $this->plugin('pager'); ?> 
