<?php Linko::Plugin()->call('activity.tpl_display_block_start'); ?>

<div id="activity-wrapper">
	<?php if($bUser): ?>
	<div id="js-user-id" style="display: none;"><?php echo $iUser; ?></div>
	<?php endif; ?>

	<div id="activity-js-new-block"></div>

    <?php if(count($aActivities)):  ?>
        <?php foreach($aActivities as $aActivity):  ?>

            <?php if($aActivity['display_activity']): ?>
                <?php $this->getTemplate($aActivity['activity_template'], array(
                    'aActivity' => $aActivity,
                    'bCommentEnabled' => $bCommentEnabled,
                    'bCanComment' => $bCanComment
                )); ?>
            <?php endif; ?>
        <?php endforeach; ?>

		<div id="activity-load-more-js-wrapper"></div>
		<div class="clear"></div>

        <a href="#" class="activity-view-more" id="activity-view-more-2">
            View More
        </a>

    <?php else: ?>
	<div class="no-item">
		<h4>No activities</h4>
	</div>
    <?php endif; ?>
</div>
<?php Linko::Plugin()->call('activity.tpl_display_block_end'); ?>