<?php
defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage menu : controller_template - admincp\action.phtml
 * @version 1.0.0
 * @copyright Netaviva (c) 2013. All Rights Reserved.
 */
?>


<form class="" action="<?php echo Linko::Url()->make('self'); ?>" method="post">
    <div class="row-fluid">
        <h3>Menu #<?php echo $iMenuId; ?> </h3>
        <div class="pull-right">
            <input type="submit" class="btn btn-primary admin-submit-button" value="<?php echo $bEdit ? 'Save' : 'Create'; ?>" />
        </div>
    </div>
    <div class="row-fluid">
        <div class="box span8" onTablet="span12" onDesktop="span8">
            <div class="box-header">
                <h2><i class="icon-edit"></i><span class="break"></span>General</h2>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <label class="control-label" for="focusedInput">Title:</label>
                    <div class="controls">
                        <input id="js-input-title" class="span12 focused" type="text" name="val[title]" value="<?php echo Arr::get($aVals, 'title', Arr::get($aMenuItem, 'menu_item_title', '')); ?>">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="focusedInput">Url:</label>
                    <div class="controls">
                        <input id="url" class="span12 focused" type="text" name="val[url]" value="<?php echo Arr::get($aVals, 'url', Arr::get($aMenuItem, 'menu_item_url', '')); ?>">
                        <small>
                            <input type="checkbox" id="js-select-page"<?php echo (Arr::get($aMenuItem, 'page_id', '') != 0 ? ' checked="checked"' : ''); ?> />
                            Or select a page
                        </small>
                    </div>
                </div>
                <div style="display: none;" id="js-page-form">
                    <div class="control-group">
                        <label class="control-label" for="page">Page:</label>
                        <div class="controls">
                            <select name="val[page_id]">
                                <option> -- Select Page --</option>
                                <?php foreach ($aPages as $aPage): ?>
                                    <option
                                        value="<?php echo $aPage['page_id']; ?>"<?php echo (Arr::get($aVals, 'page_id', Arr::get($aMenuItem, 'page_id', '')) == $aPage['page_id']) ? ' selected="selected"' : ''; ?>><?php echo $aPage['page_title']; ?></option>
                                    <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="focusedInput">Paramters:</label>
                        <div class="controls">
                            <input id="param" class="span12 focused" type="text" name="val[param]" value="<?php echo Arr::get($aVals, 'param', Arr::get($aMenuItem, 'menu_item_param', '')); ?>">
                            <small>
                                For advance users. Leave it empty if you don't know how to set this.
                            </small>
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="page">Parent Menu:</label>
                    <div class="controls">
                        <select name="val[parent_id]">
                            <option value="0"> None</option>
                            <?php foreach ($aParents as $aParent): ?>
                                <option value="<?php echo $aParent['menu_item_id']; ?>">
                                    <?php echo str_repeat(' - ', $aParent['menu_depth']); ?>
                                    <?php echo $aParent['menu_item_title']; ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="box span4 noMargin" onTablet="span12" onDesktop="span4">
            <div class="box-header">
                <h2><i class="icon-tasks"></i><span class="break"></span>Menu Options</h2>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <label class="control-label" for="page">Status:</label>
                    <div class="controls">
                        <select name="val[status]">
                            <option
                                value="1"<?php echo Arr::get($aVals, 'status', Arr::get($aMenuItem, 'menu_item_status', '')) == '1' ? ' selected="selected"' : ''; ?>>
                                Active
                            </option>
                            <option
                                value="0"<?php echo Arr::get($aVals, 'status', Arr::get($aMenuItem, 'menu_item_status', '')) == '0' ? ' selected="selected"' : ''; ?>>
                                Inactive
                            </option>
                        </select>
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="page">Target:</label>
                    <div class="controls">
                        <select name="val[target]">
                            <option
                                value="0"<?php echo Arr::get($aVals, 'target', Arr::get($aMenuItem, 'menu_item_target', '')) == 0 ? ' selected="selected"' : ''; ?>>
                                Same Window
                            </option>
                            <option
                                value="1"<?php echo Arr::get($aVals, 'target', Arr::get($aMenuItem, 'menu_item_target', '')) == 1 ? ' selected="selected"' : ''; ?>>
                                New Window
                            </option>
                        </select>
                    </div>
                </div>
            </div>
        </div>  

        <div class="box span4 noMargin" onTablet="span12" onDesktop="span4">
            <div class="box-header">
                <h2><i class="icon-filter"></i><span class="break"></span>User Access</h2>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <label class="control-label" for="pagestatus">Select Who Can See Menu:</label>
                    <div class="controls">
                        <ul class="select-blog-categories">
                            <?php foreach ($aUserRoles as $aRole): ?>
                                <label for="category-<?php echo $aRole['role_id']; ?>">
                                    <input type="checkbox" name="val[allow_access][]"<?php echo((in_array($aRole['role_id'], Arr::get($aMenuItem, 'allow_access', array())) || !$bEdit) ? ' checked="checked"' : ''); ?> value="<?php echo $aRole['role_id']; ?>"/>
                                    <?php echo $aRole['role_title']; ?>
                                </label>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</form>
<script type="text/javascript">
    if($('#js-select-page').is(':checked')){
        $('#js-page-form').show();
    }

    $('#js-select-page').change(function() {
        if($(this).is(':checked')) {
            $('#js-page-form').show();
        }
        else {
            $('#js-page-form').hide();
        }
    });
</script>