<form action="" method="post">
    <div class="row-fluid">
        <div class="pull-right">
            <input type="submit" class="btn btn-primary admin-submit-button" value="<?php echo $bEdit ? 'Save Menu' : 'Create Menu'; ?>"/>
        </div>
    </div>
    <div class="row-fluid">
        <div class="box span8" onTablet="span12" onDesktop="span8">
            <div class="box-header">
                <h2><i class="icon-edit"></i><span class="break"></span><?php echo $bEdit ? 'Edit Menu' : 'Add Menu'; ?></h2>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <label class="control-label" for="focusedInput">Title</label>
                    <div class="controls">
                        <input class="span12 focused" id="title" type="text" name="val[title]" value="<?php echo Arr::get($aVals, 'title', Arr::get($aMenu, 'menu_title', '')); ?>">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="textarea2">Theme Location:</label>
                    <div class="controls">
                        <select name="val[location]">
                            <option value="">-- Select Location --</option>
                            <?php foreach ($aLocations as $aLocation): ?>
                                <option value="<?php echo $aLocation['var']; ?>"<?php echo Arr::get($aVals, 'location', Arr::get($aMenu, 'menu_location', '')) == $aLocation['var'] ? ' selected="selected"' : ''; ?>>
                                    <?php echo $aLocation['value']; ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="box span4 noMargin" onTablet="span12" onDesktop="span4">
            <div class="box-header">
                <h2><i class="icon-tasks"></i><span class="break"></span>Options</h2>
            </div>
            <div class="box-content">
                <p>Manage links on navigation menus and all the navigation groups they belong to</p>
            </div>
        </div>  
    </div>
</form>
