<?php
defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage blog : controller_template - admincp\category\action.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>

<form class="" action="<?php echo Linko::Url()->make('self'); ?>" method="post" enctype="multipart/form-data">
    <div class="row-fluid">
        <div class="pull-right category-submit">
            <input type="submit" class="btn btn-primary admin-submit-button" value="Submit" />
        </div>
    </div>
    <div class="row-fluid">
        <div class="box span8" onTablet="span12" onDesktop="span8">
            <div class="box-header">
                <h2><i class="icon-edit"></i><span class="break"></span>Add Category</h2>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <label class="control-label" for="focusedInput">Title:</label>
                    <div class="controls">
                        <input id="js-input-title" class="span12 focused" type="text" name="val[title]" value="<?php echo Arr::get($aVals, 'title', Arr::get($aCategory, 'category_title', '')); ?>">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="focusedInput">Url Slug</label>
                    <div class="controls">
                        <input id="js-input-slug" class="span12 focused" type="text" name="val[slug]" value="<?php echo Arr::get($aVals, 'slug', Arr::get($aCategory, 'category_slug', '')); ?>">
                    </div>
                </div>
            </div>
        </div>
        <div class="box span4 noMargin" onTablet="span12" onDesktop="span4">
            <div class="box-header">
                <h2><i class="icon-tasks"></i><span class="break"></span>Options</h2>
            </div>
            <div class="box-content">
            </div>
        </div>  
    </div>
</form>

<script type="text/javascript">
    var $input_slug = $('#js-input-slug');
    $('#js-input-title').on('keyup', function(){
        $input_slug.val(Linko.util.slugify($(this).val()));
    });
</script>