<?php

defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage user : controller_template - reset-password.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>
<div class="well">
        <?php if($bResetPage): ?>
        <form id="signup" class="form-horizontal" method="post" action="<?php echo Linko::Url()->make('self'); ?>">
            <legend><?php echo Lang::t('user.just_a_step_remaining_enter_your_password_below_to_set_a_new_password'); ?></legend>
            <div class="control-group ">
                <label class="control-label"><?php echo Lang::t('user.password'); ?>:</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-lock"></i></span>
                        <input type="text" class="input-xlarge" id="password1" name="val[password]" placeholder="Password">
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"><?php echo Lang::t('user.re_enter_password'); ?>:</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-lock"></i></span>
                        <input type="text" id="passwd" class="input-xlarge" name="val[password_confirm]" placeholder="Password">
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"></label>
                <div class="controls">
                    <button type="submit" class="btn btn-success" ><?php echo Lang::t('user.reset_password'); ?></button>
                </div>

            </div>
        </form>
        <?php else: ?>
                <form id="signup" class="form-horizontal" method="post" action="<?php echo Linko::Url()->make('self'); ?>">
            <div class="control-group ">
                <label class="control-label"><?php echo Lang::t('user.email'); ?>:</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-lock"></i></span>
                        <input type="text" class="input-xlarge" id="email" name="email" placeholder="Email Address">
                        <p class="help-block"><?php echo Lang::t('user.enter_email_used_during_registeration'); ?></p>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"></label>
                <div class="controls">
                    <button type="submit" class="btn btn-success" ><?php echo Lang::t('user.request_password_reset'); ?></button>
                </div>

            </div>
        </form>
    <?php endif; ?>
    </div>