<?php defined('LINKO') or exit(); ?>
<div class="tweet_block">
    <?php if(count($tweets)): ?>
    <?php //var_dump($tweets); ?>
	<ul class="tweets">
	    <?php foreach($tweets as $tweet): ?>
		<li>
                 <div class="tweet">
                   <span class="tweet_text"><?php echo $tweet->text; ?></span>
		    <span class="tweet_time"><?php echo Html::tag('a', date("l M j \- g:ia",strtotime($tweet->created_at)), array('href' => 'https://twitter.com/' . $username . '/status/' . $tweet->id_str)); ?></span>
                 </div>
                 </li>
	    <?php endforeach; ?>
	</ul> 
   <?php endif; ?>
</div>
<div class="twitter_bottom">
	<p class="twitter_follow">
		<a href="https://twitter.com/<?php echo $username; ?>" class="twitter-follow-button" data-show-count="false" data-lang="en" data-size="large"></a>
		<script>
			!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	</p>
</div>