<div id="user-reminder-password">

	<?php if($bResetPage): ?>

	<p>
		<?php echo Lang::t('user.just_a_step_remaining_enter_your_password_below_to_set_a_new_password'); ?>
	</p>
	<form action="<?php echo Linko::Url()->make('self'); ?>" method="post">
		<div class="controls">
			<div class="control-item">
				<div class="control-item-label">
					<label><?php echo Lang::t('user.password'); ?>: </label>
				</div>
				<div class="control-item-data">
					<input type="password" name="val[password]" value="" />
				</div>
			</div>

			<div class="control-item">
				<div class="control-item-label">
					<label><?php echo Lang::t('user.re_enter_password'); ?>: </label>
				</div>
				<div class="control-item-data">
					<input type="password" name="val[password_confirm]" value="" />
				</div>
			</div>

			<div class="control-bottom">
				<input type="submit" class="button" value="<?php echo Lang::t('user.reset_password'); ?>" />
			</div>
		</div>
	</form>

	<?php else: ?>
	<form action="<?php echo Linko::Url()->make('self'); ?>" method="post">
		<div class="controls">
			<div class="control-item">
				<div class="control-item-label">
					<label><?php echo Lang::t('user.email'); ?>: </label>
				</div>
				<div class="control-item-data">
					<input type="text" name="email" value="" />
					<p>
						<?php echo Lang::t('user.enter_email_used_during_registeration'); ?>
					</p>
				</div>
			</div>

			<div class="control-bottom">
				<input type="submit" class="button" value="<?php echo Lang::t('user.request_password_reset'); ?>" />
			</div>
		</div>
	</form>
	<?php endif; ?>
</div>