<?php

defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage youmax : controller_template - index.phtml
 * @version 1.0
 * @copyright Netaviva (c) 2013. All Rights Reserved.
 */
?>
<div id="youmax"></div>

<script type="text/javascript">
 var youTubeChannelURL = '<?php echo $youtubeChannelURL; ?>';
 var youTubePlaylistURL = '<?php echo $youtubePlaylistURL; ?>';
 var youmaxDefaultTab = '<?php echo $youtubeDefaultTab; ?>';
</script>