<div class="row-fluid sortable">		
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="icon-edit"></i><span class="break"></span>Mail Settings</h2>
        </div>
        <form action="<?php echo Linko::Url()->make('self'); ?>" method="post">
            <div class="box-content">
                <table id="menu-item-list" class="table table-bordered">
                    <thead>
                    <th style="width: 20%">Mail Title</th>
                    <th style="width: 30%">Mail Description</th>
                    <th style="width: 50%"></th>
                    </thead>   
                    <tbody>
                        <?php foreach ($aMails as $aMail): ?>
                            <tr>
                                <td>
                                    <h3><?php echo $aMail['mail_title']; ?></h3>
                                </td>
                                <td><?php echo $aMail['mail_description']; ?></td>
                                <td>
                                    <div class="control-group">
                                        <label class="control-label" for="focusedInput">Subject</label>
                                        <div class="controls">
                                            <input class="span12 focused" type="text" name="email[<?php echo $aMail['mail_var']; ?>][subject]" value="<?php echo $aMail['mail_subject']; ?>">
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="textarea2">Body</label>
                                        <div class="controls">
                                            <textarea class="span12" id="textarea2" rows="10" name="email[<?php echo $aMail['mail_var']; ?>][body]"><?php echo $aMail['mail_body']; ?></textarea>
                                        </div>
                                    </div>

                                </td>
                            </tr>  
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <input class="btn btn-info btn-small" type="submit" value="Submit" />
            </div>
        </form>
    </div><!--/span-->                   
</div><!--/row-->
