<h1 class="profile-title"><?php echo Lang::t('gamification.my-badges')?></h1>

<?php foreach($aBadges as  $key=>$badge):?>

    <?php $aBadgeDetails = Linko::Model('gamification/badge')->get($badge['badge_id'])?>

    <div class="each-badges">
        <img title="<?php echo $aBadgeDetails['badge_name']?>" src="<?php  echo ($this->getImage(array('path' => $aBadgeDetails['badge_icon'], 'size' => 100), 'gamification_image')); ?>" />
        <br/>
        <h4><?php echo $aBadgeDetails['badge_name']?></h4>
    </div>
<?php endforeach?>
<div class="clear"></div>