<div id="messages-wrapper" class="clearfix">

    <?php echo $this->getTemplate('messages/controller/_layout/header', array('aUser' => $aUser),true)?>


    <?php if(empty($aMessages)):?>


        <?php echo Lang::t('messages.empty-messages')?>
    <?php else:?>

    <div id="messages-entity-wrapper">

        <?php foreach($aMessagesEntity as $key=>$aValue):?>
            <?php echo $this->getTemplate('messages/controller/_layout/message_entity',array('aEntity' => $aValue),false)?>
        <?php endforeach?>
    </div>
    <div id="messages-conversation-wrapper">

        <div id="main-messages-conversation-div">


            <?php foreach($aMessages as $k => $aValue):?>


                <?php echo $this->getTemplate('messages/controller/_layout/message_content',array('aContent' => $aValue),false)?>
            <?php endforeach?>

            </div>
            <?php echo $this->getTemplate('messages/controller/_layout/message_post_form',array('aUser' => $aUser),false)?>

    </div>

    <?php endif?>
</div>