<?php
defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage user : controller_template - admincp\role\index.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>

<div class="row-fluid sortable">		
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="icon-edit"></i><span class="break"></span>User Roles</h2>
        </div>
        <div class="box-content">
            <table id="menu-item-list" class="table table-bordered">
                <thead>
                <th>Role ID#</th>
                <th>Title</th>
                <th>Type</th>
                <th></th>
                </thead>   
                <tbody>
                    <?php foreach ($aUserRoles as $aRole): ?>
                        <tr>
                            <td><?php echo $aRole['role_id']; ?>#</td>
                            <td><?php echo $aRole['role_title']; ?></td>
                            <td><?php if ($aRole['system'] == 1): ?>
                                    System Core
                                <?php else: ?>
                                    User Defined
                                <?php endif; ?>
                            </td>
                            <td>
                              <!--<a href="<?php echo Linko::Url()->make('user:admincp:role:action', array('action' => 'edit', 'id' => $aRole['role_id'])); ?>">Edit</a>
                                <?php if ($aRole['system'] == 0): ?>
                    |
                                    <a href="<?php echo Linko::Url()->make('user:admincp:role:action', array('action' => 'delete', 'id' => $aRole['role_id'])); ?>">Delete</a>
                                <?php endif; ?> -->
                            </td>

                        </tr>  
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div><!--/span-->                   
</div><!--/row-->