<?php
defined('LINKO') or exit();
/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage blog : controller_template - admincp\action.phtml
 * @version 1.0.0
 * @copyright Netaviva (c) 2013. All Rights Reserved.
 */
?>

<form action="<?php echo Linko::Url()->make('gamification:admincp:badge', array('action' => 'edit', 'id' => $aDetails['badge_id'])) ?>" method="post" enctype="multipart/form-data">
    <div class="row-fluid">
        <div class="pull-right">
            <input type="submit" class="btn btn-primary admin-submit-button" value="Save" />
        </div>
    </div>
    <div class="row-fluid">
        <div class="box span8" onTablet="span12" onDesktop="span8">
            <div class="box-header">
                <h2><i class="icon-edit"></i><span class="break"></span>Edit Gamification Activity</h2>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <label class="control-label" for="focusedInput">Badge Name</label>
                    <div class="controls">
                        <input type="text" name="val[badge-name]" value="<?php echo $aDetails['badge_name'] ?>" class="input" size="40">
                        <input type="hidden" name="val[badge-ref]" value="<?php echo $aDetails['badge_ref'] ?>" class="input" size="40">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="focusedInput">Activity Count Limit(eg 10)</label>
                    <div class="controls">
                        <input type="text" name="val[badge-limit]" value="<?php echo $aDetails['activity_limit'] ?>" class="input" size="40">
                    </div>
                </div>
                 <?php if (Linko::Model('gamification/point')->usePointSystem()): ?>
                <div class="control-group">
                    <label class="control-label" for="pointuser">Point To Award User</label>
                    <div class="controls">
                          <input type="text" name="val[point]" value="<?php echo $aDetails['badge_point'] ?>" class="input" size="40">
                    </div>
                </div>   
            <?php endif ?>
            </div>
        </div>
        <div class="box span4 noMargin" onTablet="span12" onDesktop="span4">
            <div class="box-header">
                <h2><i class="icon-picture"></i><span class="break"></span>Change Badge Icon</h2>
            </div>
            <div class="box-content">
                <div class="control-group">
                    <div class="controls">
                        <input type="file" class="input-file" name="image" />
                    </div>
                     <img src="<?php echo ($this->getImage(array('path' => $aDetails['badge_icon'], 'size' => 100), 'gamification_image')); ?>" />
                </div>
            </div>
        </div>  

    </div>
</form>