<?php echo $this->getTemplate('profile/controller/menu',array('current' => $current))?>

<?php foreach($aResult as $aUser):?>

    <div class="each-subscription-user">

            <a title="<?php echo  ucwords($aUser['firstname'].' '.$aUser['lastname'])?>" href="<?php echo Linko::Url()->make('user:profile', array('username' => $aUser['username']));?>" ><img src="<?php echo $this->getImage(array('user' => $aUser, 'size' => 100), 'user_image')?>"/></a>
    </div>


<?php endforeach?>

<?php $this->plugin('pager'); ?>