<?php defined('LINKO') or exit; ?>
<div class="clearfix"></div>
<footer>
    <p>
        <span style="text-align:left;float:left">&copy; <a href="http://netaviva.net" target="_blank">Netaviva</a></span>
        <span style="text-align:right;float:right">Powered by:<a href="http://linkodev.com">LinkoPlatform</a></span>
    </p>

</footer>
</div><!--/.fluid-container-->
<script type="text/javascript" src="<?php echo $this->getThemeUrl(); ?>js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->getThemeUrl(); ?>js/script.js"></script>
<script type="text/javascript" src="<?php echo $this->getThemeUrl(); ?>js/jquery.uniform.min.js"></script>
<?php echo $this->getFooter(); ?>
</body>
</html>