<?php
/**
 * @var $this Linko_Application_Template
 */
defined('LINKO') or exit();

Linko::Template()
        ->setStyle(array('jquery/chosen/chosen.css'), 'asset_css')
        ->setStyle(array('style-responsive.css'), 'theme_css')
        ->setScript(array('jquery/chosen.jquery.min.js'), 'asset_js', 'header');

if (isset($layout) && $layout == 'login') {
    Linko::Template()->setStyle('login.css', 'theme_css');
}
?>
<!DOCTYPE html>
<html>
    <head>
        <title><?php echo $this->getTitle(); ?></title>
        <!-- start: Mobile Specific -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- end: Mobile Specific -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->getThemeUrl(); ?>css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->getThemeUrl(); ?>css/bootstrap-responsive.min.css">
        <?php echo $this->getHeader(); ?>
    </head>
    <body>
        <!--        <div id="overlay">
                    <ul>
                        <li class="li1"></li>
                        <li class="li2"></li>
                        <li class="li3"></li>
                        <li class="li4"></li>
                        <li class="li5"></li>
                        <li class="li6"></li>
                    </ul>
                </div>	-->
        <!-- start: Header -->
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo Linko::Url()->make('admincp'); ?>"><span class="hidden-phone">LinkoPlatform</span></a>

                    <!-- start: Header Menu -->
                    <div class="nav-no-collapse header-nav">
                        <ul class="nav">
                            <?php foreach (Linko::Model('Admincp')->getMenu(array('required_modules')) as $sTitle => $mLink): ?>
                                <?php if (is_array($mLink)): ?>
                                    <li class="dropdown <?php echo(is_array($mLink) ? 'has-dropdown' : ''); ?>">    
                                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                                            <span class=""><?php echo $sTitle; ?></span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <?php foreach ($mLink as $sTitle2 => $mLink2): ?>
                                                <li><a href="<?php echo $mLink2; ?>"><i class=""></i><?php echo $sTitle2; ?></a></li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </li>
                                <?php else: ?>
                                    <li><a class="btn" href="<?php echo $mLink; ?>"><span><?php echo $sTitle; ?></span></a></li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                       <?php if (Linko::Model('user/auth')->isUser()): ?>
                        <!-- start: User Dropdown -->
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="icon-user icon-white"></i>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo Linko::Url()->make(); ?>"><i class="icon-off"></i> View Website</a></li>
                                    <li><a href="<?php echo Linko::Url()->make('user:profile', array('username' => Linko::Model('User/Auth')->getUserBy('username'))); ?>"><i class="icon-user"></i> Profile</a></li>
                                    <li><a href="<?php echo Linko::Url()->make('user:logout'); ?>"><i class="icon-off"></i> Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                        <!-- end: User Dropdown -->
                      <?php endif ?>
                    </div>
                    <!-- end: Header Menu -->
                </div>
            </div>
        </div>
        <!-- start: Header -->