<?php defined('LINKO') or exit(); ?>

<?php $this->getLayout('header'); ?>
<div class="container-fluid">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div class="span2 main-menu-span">
            <div class="nav-collapse sidebar-nav">
                <ul class="nav nav-tabs nav-stacked main-menu">
                    <?php foreach (Linko::Model('Admincp')->getMenu(array('main', 'other_modules')) as $sTitle => $mLink): ($bSub = (is_array($mLink) ? true : false)); ?>
                        <?php if ($bSub): ?>    
                            <li class="<?php echo $bSub ? 'drop-menu' : ''; ?>">
                                <a class="dropmenu" href="#"><i class="icon-plus-sign icon-white"></i><span class="hidden-tablet"><?php echo $sTitle; ?></span></a>
                                <ul>
                                    <?php foreach ($mLink as $sTitle2 => $mLink2): ?>
                                        <li><a class="submenu" href="<?php echo $mLink2; ?>"><i class="fa-icon-file-alt"></i><span class="hidden-tablet"> <?php echo $sTitle2; ?></span></a></li>
                                    <?php endforeach; ?>
                                </ul>
                            </li>
                        <?php else: ?>
                            <li><a href="<?php echo $mLink; ?>"><i class="icon-stop icon-white"></i><span class="hidden-tablet"> <?php echo $sTitle; ?></span></a></li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
        <!-- end: Main Menu -->

        <noscript>
        <div class="alert alert-block span10">
            <h4 class="alert-heading">Warning!</h4>
            <p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
        </div>
        </noscript>

        <div id="content" class="span10">
            <!-- start: Content -->
            <div class="row-fliud">
                <ul class="breadcrumb">
                    <?php $this->plugin('breadcrumb', array('links' => false)); ?>
                </ul>
            </div>
            <?php $this->plugin('flash'); ?>
            <?php $this->plugin('error'); ?>
            <?php echo $this->getContent(); ?>
            <!-- end: Content -->
        </div><!--/#content.span10-->
    </div><!--/fluid-row-->
    <?php $this->getLayout('footer'); ?>