<?php
defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage locale : controller_template - admincp\translation\module.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>


    <div class="row-fluid sortable">		
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="icon-edit"></i><span class="break"></span>Translations (<?php echo $sModule; ?>)</h2>
            </div>
            <div class="box-content">
                <table id="menu-item-list" class="table table-striped table-bordered">
                    <thead>
                    <th></th>
                    <th style="width:15%;">Reference Key</th>
                    <th style="width:35%;">Translation</th>
                    <th style="width:45%;">Edit</th>
                    </thead>   
                    <tbody>
                        <?php foreach ($aTranslations as $aTrans): ?>
                            <tr class="<?php echo $this->plugin('cycle', array('value' => 'odd,even')); ?>">
                                <td><input type="checkbox" name="var[]" value="<?php echo $aTrans['translation_var']; ?>" /></td>
                                <td><?php echo $aTrans['translation_var']; ?></td>
                                <td><?php echo $aTrans['translation_value']; ?></td>
                                <td>
                                    <div class="control-group">
                                        <div class="controls">
                                            <textarea class="span12" name="val[<?php echo $aTrans['translation_var']; ?>]"><?php echo $aTrans['translation_value']; ?></textarea>
                                        </div>
                                    </div>
                                </td>
                            </tr>  
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php echo $this->plugin('pager'); ?>
                <div class="pull-right action-dropdown">
                    <input type="submit" class="btn btn-info" name="act[save_selected]" value="Save Selected" />
                    <input type="submit" class="btn btn-danger" name="act[delete_selected]" value="Delete Selected" />
                    <input type="submit" class="btn" name="act[save_all]" value="Save All" />    
                </div>
            </div>
        </div><!--/span-->                   
    </div><!--/row-->
</form>