<?php
defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage locale : controller_template - admincp\index.phtml
 * @version 1.0.0
 * @copyright Netaviva (c) 2013. All Rights Reserved.
 */
?>
<div class="row-fluid sortable">		
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="icon-edit"></i><span class="break"></span>Supported Locales</h2>
        </div>
        <div class="box-content">
            <table id="menu-item-list" class="table table-striped table-bordered">
                <thead>
                <th>ISO Abbreviation</th>
                <th>Title</th>
                <th></th>

                </thead>   
                <tbody>
                    <?php foreach ($aLanguages as $aLanguage): ?>
                        <tr>
                            <td><?php echo $aLanguage['locale_id']; ?></td>
                            <td><?php echo $aLanguage['title']; ?></td>
                            <td>
                                <a class="btn btn-mini btn-inverse" href="#">
                                    <i class="">Edit</i>
                                </a>
                                <a class="btn btn-mini btn-danger" href="#">
                                    <i class="">Delete</i> 
                                </a>
                            </td>
                        </tr>  
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div><!--/span-->                   
</div><!--/row-->