<?php

defined('LINKO') or exit();

/**
 * @author LinkoDEV Team
 * @package linkocms
 * @subpackage user : controller_template - setting\photo.phtml
 * @version 1.0.0
 * @copyright Copyright (c) 2013. All Rights Reserved.
 */
?>

<div class="user-setting-photo">
    <form action="<?php echo Linko::Url()->make('self'); ?>" method="post" enctype="multipart/form-data">
        <div class="controls">
	        <div class="control-item">
                <div class="control-item-label">
                    &nbsp;
                </div>
                <div class="control-item-data">
	                <input type="file" name="image" />
                </div>
	        </div>
	        <div class="control-bottom">
		        <input class="button" type="submit" name="upload_photo" value="Upload" />
	        </div>
        </div>
    </form>

    <h4>Current Photo</h4>
    <img src="<?php echo $this->getImage(array('user' => $aUser), 'user_image'); ?>" />
</div>